"""add image_url to anime

Revision ID: 8054b131010c
Revises: a3a58ace3ca5
Create Date: 2026-07-10 12:13:46.246739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8054b131010c'
down_revision: Union[str, Sequence[str], None] = 'a3a58ace3ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'image_url')
    # ### end Alembic commands ###
