"""initial schema: anime, reception_signals

Revision ID: a3a58ace3ca5
Revises: 59d8c41aa8a1
Create Date: 2026-07-08 14:23:38.497144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a3a58ace3ca5'
down_revision: Union[str, Sequence[str], None] = '59d8c41aa8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('aired_from', sa.Date(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('score_stddev', sa.Numeric(), nullable=True),
    sa.Column('popularity_rank', sa.Integer(), nullable=True),
    sa.Column('synopsis_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reception_signals',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('review_sentiment_ratio', sa.Numeric(), nullable=True),
    sa.Column('reception_summary', sa.Text(), nullable=True),
    sa.Column('community_flag', sa.Enum('none', 'mixed', 'widely_criticized', name='community_flag'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime.id'], ),
    sa.PrimaryKeyConstraint('anime_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reception_signals')
    op.drop_table('anime')
    # ### end Alembic commands ###
